# Generated by Django 6.0 on 2026-01-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
