# Generated by Django 6.0 on 2026-01-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_email_options_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/project_pictures'),
        ),
    ]
