# Generated by Django 6.0 on 2026-01-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_hero_service_teammember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedschedule',
            unique_together=set(),
        ),
    ]
